{
	"version": 1761840178,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/platform-sheet0.png",
		"images/coin-sheet0.png",
		"images/background-sheet0.png",
		"images/blockage-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sun-sheet0.png",
		"images/mountain-sheet0.png",
		"images/fire-sheet0.png",
		"images/power-sheet0.png",
		"images/bomb-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/play-sheet0.png",
		"images/high-sheet0.png",
		"images/submitscore-sheet0.png",
		"images/more_games-sheet0.png",
		"images/top10-sheet0.png",
		"images/mainmenu2-sheet0.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/game_over-sheet0.png",
		"images/blank-sheet0.png",
		"images/loading-sheet0.png",
		"images/submit-sheet0.png",
		"images/black2-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/minus-sheet0.png",
		"images/brandinglogo-sheet0.png",
		"images/sound_mute-sheet0.png",
		"images/sound_mute-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/submit1-sheet0.png",
		"media/bump4.m4a",
		"media/bump4.ogg",
		"media/ok - 2.m4a",
		"media/ok - 2.ogg",
		"media/oops3.m4a",
		"media/oops3.ogg",
		"media/retrolaser1.m4a",
		"media/retrolaser1.ogg",
		"media/tronblast1.m4a",
		"media/tronblast1.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/no.m4a",
		"media/no.ogg",
		"media/mattoglseby.m4a",
		"media/mattoglseby.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}